### ISSUE TITLE
ValueError: offset must be a timedelta strictly between

### ISSUE THREAD

**Issue by MarpleA** [ekspla/Read-Symbian-SportsTracker-file#16] opened 2022-04-22 21:47 UTC
I get the following error message when trying to convert a file:

`Traceback (most recent call last):
  File "/usr/local/bin/convert_nst_files_to_gpx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/symbian_sports_tracker/convert_nst_files_to_gpx.py", line 245, in main
    nst.add_gpx_summary(gpx, trackpt_store)
  File "/usr/local/lib/python3.8/dist-packages/symbian_sports_tracker/nst.py", line 227, in add_gpx_summary
    START_TIME, dt.timezone(dt.timedelta(hours=TZ_HOURS), ))
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24), not datetime.timedelta(days=-67093011, seconds=56501, microseconds=999760).`

any idea what's wrong?

Best

**Comment by ekspla** [comment] 2022-04-22 22:55
Timezone information (including DST) is not stored in the track data.  TZ_HOURS (time zone in hours, from -24 to 24) is calculated as the following way by using START_LOCALTIME and START_TIME (in UTC) (see, line 157 of convert_nst_files_to_gpx.py ):

   nst.TZ_HOURS = int(nst.START_LOCALTIME - nst.START_TIME) / 3600

There is something wrong in the stored data (i.e. corrupted) of either START_LOCALTIME or START_TIME in your track file (.DAT file).  Can you upload your track file?


You can see the stored START_TIME and START_LOCALTIME, in a human readable format, by editing the lines shown below because they are commented out (by eliminating the preceding #).

(line 153)
    #print(f'Start Z: {nst.format_datetime(nst.START_TIME)}Z')
(line 112)
    #print(f'Start: {nst.format_datetime(nst.START_LOCALTIME)}+09:00')

Best wishes

**Comment by MarpleA** [comment] 2022-04-28 09:56
hi,

is there a way I can send you this file privately?

**Comment by ekspla** [comment] 2022-04-28 11:00
You can send me an e-mail personally with the track file as an attachment.  E-mail addresses are shown in logs if you clone repositories in Github. 

Best wishes

**Comment by MarpleA** [comment] 2022-04-28 21:56
sorry, but I can't find any mail addresses under .git/logs

**Comment by ekspla** [comment] 2022-04-29 01:06
Clone, change directory, and type git log.

Regards

**Comment by ekspla** [comment] 2022-05-01 05:39
A summary of this issue:

It was found that the error is caused by the preceding  SCSU encoded track name of variable length.
The name was supposed to be a fixed length of date/time, e.g. '24/12/2019 12:34'(24 hr format, 16 bytes).
But it can be a format like  '24/12/2019 11:34 pm'(19 bytes), '24/12/2019 9:34 am'(18 bytes), etc.
depending on date/time format of Symbian OS.

So, the start/stop time after the track name is not necessarily be located at a fixed address of 0x018e or
0x018e + 0x4.  It should be defined as a relative address.

I am not quite sure if the other data fields that are defined in my script as fixed addresses may cause
such errors.  The patch I commit is merely a fix to the address of start/stop Z time (UTC), and the patched
codes are tested for MarpleA's track files.

**Comment by ekspla** [comment] 2022-05-01 06:49
The script was fixed thanks @MarpleA .  I will close this case.

**Closed** 2022-05-01 06:49 UTC
Labels: bug
